---
- name: Clone libphutil
  git:
    repo: git://github.com/facebook/libphutil
    dest: /srv/www/libphutil

- name: Clone arcanist
  git:
    repo: git://github.com/facebook/arcanist
    dest: /srv/www/arcanist

- name: Clone phabricator to {{ phabricator_path }}
  git:
    repo: git://github.com/facebook/phabricator
    dest: "{{ phabricator_path }}"

- name: Place a config in {{ phabricator_path }}conf/default.conf.php
  template:
    src: myconfig.conf.php
    dest: "{{ phabricator_path }}conf/default.conf.php"

- name: Migrate the database
  command: chdir={{ phabricator_path }} ./bin/storage upgrade --force

- name: Start phabricator daemons
  command: chdir={{ phabricator_path }} ./bin/phd start

- name: Create the repository directory
  file:
    path: "{{ repositories_path }}"
    state: directory
