---
- name: Update apt cache
  sudo: yes
  apt:
    update_cache: yes

- name: Update all packages to the latest version
  sudo: yes
  apt:
    upgrade: dist

- name: Install dependency
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - git

- name: Add alias to 127.0.0.1 to /etc/hosts
  sudo: yes
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1 {{ domain }}"
    line: "127.0.0.1 {{ domain }}"
    state: present
