---
- name: Install php-fpm and deps
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - php5
    - php5-fpm
    - php5-mysql
    - php5-gd
    - php-apc
    - php5-curl
    - php5-cli
    - php5-json

- name: Copy php.ini configuration
  template:
    src: php.ini
    dest: /etc/php5/fpm/php.ini
  notify: restart php-fpm
