- name: update apt
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: install pycurl
  sudo: yes
  apt:
    pkg: python-pycurl
    state: latest

- name: configure repository preferences
  sudo: yes
  with_items: apt_preferences
  template:
    src: preferences.pref.j2
    dest: "/etc/apt/preferences.d/{{ item.name }}.pref"
    owner: root
    group: root
