---
- name: Install MySQL package
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
   - mysql-server

- name: Create MySQL configuration file
  sudo: yes
  template:
    src: my.cnf
    dest: /etc/my.cnf
  notify:
  - restart mysql

- name: Start MySQL Service
  sudo: yes
  service:
    name: mysql
    state: started
    enabled: true


